package com.unlam.feat.ui.util

sealed class TypeValueChange {
    object OnValueChangeEmail : TypeValueChange()
    object OnValueChangeReEmail : TypeValueChange()
    object OnValueChangeRePassword : TypeValueChange()
    object OnValueChangePassword : TypeValueChange()
    object OnValueChangeLastName : TypeValueChange()
    object OnValueChangeName : TypeValueChange()
    object OnValueChangeNickname : TypeValueChange()
    object OnValueChangeSex : TypeValueChange()
    object OnValueChangeDate : TypeValueChange()
    object OnValueChangeAddressAlias : TypeValueChange()
    object OnValueChangeStartTime : TypeValueChange()
    object OnValueChangeEndTime : TypeValueChange()
    object OnValueChangePeriodicity : TypeValueChange()
    object OnValueChangeAddress : TypeValueChange()
    object OnValueChangePosition : TypeValueChange()
    object OnValueChangeDescription : TypeValueChange()
    object OnValueChangeOrganizer : TypeValueChange()
    object OnValueChangeSportGeneric : TypeValueChange()
    object OnValueChangeTypeSport : TypeValueChange()
    object OnValueChangeSundayIsChecked: TypeValueChange()
    object OnValueChangeStartTimeSunday : TypeValueChange()
    object OnValueChangeEndTimeSunday : TypeValueChange()
    object OnValueChangeMondayIsChecked: TypeValueChange()
    object OnValueChangeStartTimeMonday : TypeValueChange()
    object OnValueChangeEndTimeMonday : TypeValueChange()
    object OnValueChangeTuesdayIsChecked: TypeValueChange()
    object OnValueChangeStartTimeTuesday : TypeValueChange()
    object OnValueChangeEndTimeTuesday : TypeValueChange()
    object OnValueChangeWednesdayIsChecked: TypeValueChange()
    object OnValueChangeStartTimeWednesday : TypeValueChange()
    object OnValueChangeEndTimeWednesday: TypeValueChange()
    object OnValueChangeThursdayIsChecked: TypeValueChange()
    object OnValueChangeStartTimeThursday : TypeValueChange()
    object OnValueChangeEndTimeThursday : TypeValueChange()
    object OnValueChangeFridayIsChecked: TypeValueChange()
    object OnValueChangeStartTimeFriday : TypeValueChange()
    object OnValueChangeEndTimeFriday : TypeValueChange()
    object OnValueChangeSaturdayIsChecked: TypeValueChange()
    object OnValueChangeStartTimeSaturday : TypeValueChange()
    object OnValueChangeEndTimeSaturday : TypeValueChange()
    object OnValueChangeDay: TypeValueChange()
    object OnValueChangeDistance: TypeValueChange()

}