package com.unlam.feat.model.request

data class RequestPersonTransaction(
    val userUid: String,
    val lastName: String,
    val name: String,
    val dateOfBirth: String,
    val nickname: String,
    val sex: String,
    val latitude: String,
    val longitude: String,
    val address: String,
    val addressAlias: String?,
    val startTimeSunday: String?,
    val endTimeSunday: String?,
    val startTimeMonday: String?,
    val endTimeMonday: String?,
    val startTimeTuesday: String?,
    val endTimeTuesday: String?,
    val startTimeWednesday: String?,
    val endTimeWednesday: String?,
    val startTimeThursday: String?,
    val endTimeThursday: String?,
    val startTimeFriday: String?,
    val endTimeFriday: String?,
    val startTimeSaturday: String?,
    val endTimeSaturday: String?,
    val minAge: String,
    val maxAge: String,
    val notifications: Boolean,
    val willingDistance: String,
    val idSoccer:String?,
    val abilitiesSoccer:String?,
    val positionIdSoccer:Int?,
    val levelIdSoccer:Int?,
    val valuationIdSoccer:Int?,

    val idBasketball:String?,
    val abilitiesBasketball:String?,
    val positionIdBasketball:Int?,
    val levelIdBasketball:Int?,
    val valuationIdBasketball:Int?,

    val idPadel:String?,
    val abilitiesPadel:String?,
    val positionIdPadel:Int?,
    val levelIdPadel:Int?,
    val valuationIdPadel:Int?,

    val idTennis:String?,
    val abilitiesTennis:String?,
    val positionIdTennis:Int?,
    val levelIdTennis:Int?,
    val valuationIdTennis:Int?,

    val idRecreationalActivity:String?,
    val abilitiesRecreationalActivity:String?,
    val positionIdRecreationalActivity:Int?,
    val levelIdRecreationalActivity:Int?,
    val valuationIdRecreationalActivity:Int?,

    )